<?php

namespace ContainerPxokFAr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAddProductReviewHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\Bundle\ApiBundle\CommandHandler\AddProductReviewHandler' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\CommandHandler\AddProductReviewHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/CommandHandler/AddProductReviewHandler.php';

        return $container->privates['Sylius\\Bundle\\ApiBundle\\CommandHandler\\AddProductReviewHandler'] = new \Sylius\Bundle\ApiBundle\CommandHandler\AddProductReviewHandler(($container->services['sylius.factory.product_review'] ?? $container->load('getSylius_Factory_ProductReviewService')), ($container->services['sylius.repository.product_review'] ?? $container->load('getSylius_Repository_ProductReviewService')), ($container->services['sylius.repository.product'] ?? $container->load('getSylius_Repository_ProductService')), ($container->privates['Sylius\\Bundle\\ApiBundle\\Provider\\CustomerProviderInterface'] ?? $container->load('getCustomerProviderInterfaceService')));
    }
}
