<?php

namespace ContainerPxokFAr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_Doctrine_Orm_Default_SubresourceDataProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'api_platform.doctrine.orm.default.subresource_data_provider' shared service.
     *
     * @return \ApiPlatform\Core\Bridge\Doctrine\Orm\SubresourceDataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Bridge/Doctrine/Common/Util/IdentifierManagerTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/Bridge/Doctrine/Orm/SubresourceDataProvider.php';

        return $container->privates['api_platform.doctrine.orm.default.subresource_data_provider'] = new \ApiPlatform\Core\Bridge\Doctrine\Orm\SubresourceDataProvider(($container->services['doctrine'] ?? $container->getDoctrineService()), ($container->privates['api_platform.metadata.property.name_collection_factory.cached'] ?? $container->getApiPlatform_Metadata_Property_NameCollectionFactory_CachedService()), ($container->privates['api_platform.metadata.property.metadata_factory.cached'] ?? $container->getApiPlatform_Metadata_Property_MetadataFactory_CachedService()), new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->services['sylius.api.doctrine.query_collection_extension.hide_archived_shipping_method'] ?? ($container->services['sylius.api.doctrine.query_collection_extension.hide_archived_shipping_method'] = new \Sylius\Bundle\ApiBundle\Doctrine\QueryCollectionExtension\HideArchivedShippingMethodExtension('App\\Entity\\Shipping\\ShippingMethod')));
            yield 1 => ($container->services['sylius.api.doctrine.query_collection_extension.accepted_product_reviews'] ?? ($container->services['sylius.api.doctrine.query_collection_extension.accepted_product_reviews'] = new \Sylius\Bundle\ApiBundle\Doctrine\QueryCollectionExtension\AcceptedProductReviewsExtension('App\\Entity\\Product\\ProductReview')));
            yield 2 => ($container->services['sylius.api.doctrine.query_collection_extension.addresses'] ?? $container->load('getSylius_Api_Doctrine_QueryCollectionExtension_AddressesService'));
            yield 3 => ($container->services['sylius.api.doctrine.query_collection_extension.products_by_channel_and_locale_code'] ?? $container->load('getSylius_Api_Doctrine_QueryCollectionExtension_ProductsByChannelAndLocaleCodeService'));
            yield 4 => ($container->services['sylius.api.doctrine.query_collection_extension.orders_by_logged_in_user'] ?? $container->load('getSylius_Api_Doctrine_QueryCollectionExtension_OrdersByLoggedInUserService'));
            yield 5 => ($container->services['sylius.api.doctrine.query_collection_extension.products_with_enable_flag'] ?? $container->load('getSylius_Api_Doctrine_QueryCollectionExtension_ProductsWithEnableFlagService'));
            yield 6 => ($container->privates['api_platform.doctrine.orm.query_extension.filter'] ?? $container->load('getApiPlatform_Doctrine_Orm_QueryExtension_FilterService'));
            yield 7 => ($container->privates['api_platform.doctrine.orm.query_extension.filter_eager_loading'] ?? $container->load('getApiPlatform_Doctrine_Orm_QueryExtension_FilterEagerLoadingService'));
            yield 8 => ($container->privates['api_platform.doctrine.orm.query_extension.eager_loading'] ?? $container->load('getApiPlatform_Doctrine_Orm_QueryExtension_EagerLoadingService'));
            yield 9 => ($container->privates['api_platform.doctrine.orm.query_extension.order'] ?? $container->load('getApiPlatform_Doctrine_Orm_QueryExtension_OrderService'));
            yield 10 => ($container->privates['api_platform.doctrine.orm.query_extension.pagination'] ?? $container->load('getApiPlatform_Doctrine_Orm_QueryExtension_PaginationService'));
        }, 11), new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->services['sylius.api.doctrine.query_item_extension.get_order'] ?? $container->load('getSylius_Api_Doctrine_QueryItemExtension_GetOrderService'));
            yield 1 => ($container->services['sylius.api.doctrine.query_item_extension.delete_order'] ?? $container->load('getSylius_Api_Doctrine_QueryItemExtension_DeleteOrderService'));
            yield 2 => ($container->privates['api_platform.doctrine.orm.query_extension.eager_loading'] ?? $container->load('getApiPlatform_Doctrine_Orm_QueryExtension_EagerLoadingService'));
        }, 3));
    }
}
