<?php

namespace ContainerPxokFAr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResetPasswordHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\Bundle\ApiBundle\CommandHandler\ResetPasswordHandler' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\CommandHandler\ResetPasswordHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/CommandHandler/ResetPasswordHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/resource-bundle/src/Component/Metadata/MetadataInterface.php';

        return $container->privates['Sylius\\Bundle\\ApiBundle\\CommandHandler\\ResetPasswordHandler'] = new \Sylius\Bundle\ApiBundle\CommandHandler\ResetPasswordHandler(($container->services['sylius.repository.shop_user'] ?? $container->load('getSylius_Repository_ShopUserService')), ($container->privates['sylius.resource_registry'] ?? $container->getSylius_ResourceRegistryService())->get('sylius.shop_user'), ($container->services['sylius.security.password_updater'] ?? $container->load('getSylius_Security_PasswordUpdaterService')));
    }
}
