<?php

namespace ContainerPxokFAr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResendVerificationEmailHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\Bundle\ApiBundle\CommandHandler\ResendVerificationEmailHandler' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\CommandHandler\ResendVerificationEmailHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/CommandHandler/ResendVerificationEmailHandler.php';

        return $container->privates['Sylius\\Bundle\\ApiBundle\\CommandHandler\\ResendVerificationEmailHandler'] = new \Sylius\Bundle\ApiBundle\CommandHandler\ResendVerificationEmailHandler(($container->services['sylius.repository.shop_user'] ?? $container->load('getSylius_Repository_ShopUserService')), ($container->services['sylius.shop_user.token_generator.email_verification'] ?? $container->load('getSylius_ShopUser_TokenGenerator_EmailVerificationService')), ($container->services['messenger.default_bus'] ?? $container->getMessenger_DefaultBusService()));
    }
}
