<?php

namespace ContainerPxokFAr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authentication_Provider_Rememberme_ShopService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.authentication.provider.rememberme.shop' shared service.
     *
     * @return \Symfony\Component\Security\Core\Authentication\Provider\RememberMeAuthenticationProvider
     *
     * @deprecated Since symfony/security-bundle 5.3: The "security.authentication.provider.rememberme.shop" service is deprecated, use the new authenticator system instead.
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('symfony/security-bundle', '5.3', 'The "security.authentication.provider.rememberme.shop" service is deprecated, use the new authenticator system instead.');

        return $container->privates['security.authentication.provider.rememberme.shop'] = new \Symfony\Component\Security\Core\Authentication\Provider\RememberMeAuthenticationProvider(($container->privates['SyliusLabs\\Polyfill\\Symfony\\Security\\Core\\User\\UserChecker'] ?? $container->load('getUserCheckerService')), $container->getEnv('APP_SECRET'), 'shop');
    }
}
