<?php

namespace ContainerPxokFAr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendOrderConfirmationHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\Bundle\ApiBundle\CommandHandler\SendOrderConfirmationHandler' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\CommandHandler\SendOrderConfirmationHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/CommandHandler/SendOrderConfirmationHandler.php';

        return $container->privates['Sylius\\Bundle\\ApiBundle\\CommandHandler\\SendOrderConfirmationHandler'] = new \Sylius\Bundle\ApiBundle\CommandHandler\SendOrderConfirmationHandler(($container->services['sylius.email_sender'] ?? $container->load('getSylius_EmailSenderService')), ($container->services['sylius.repository.order'] ?? $container->getSylius_Repository_OrderService()));
    }
}
