<?php

namespace ContainerPxokFAr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendAccountRegistrationEmailHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Sylius\Bundle\ApiBundle\CommandHandler\SendAccountRegistrationEmailHandler' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\CommandHandler\SendAccountRegistrationEmailHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/CommandHandler/SendAccountRegistrationEmailHandler.php';

        return $container->privates['Sylius\\Bundle\\ApiBundle\\CommandHandler\\SendAccountRegistrationEmailHandler'] = new \Sylius\Bundle\ApiBundle\CommandHandler\SendAccountRegistrationEmailHandler(($container->services['sylius.repository.shop_user'] ?? $container->load('getSylius_Repository_ShopUserService')), ($container->services['sylius.repository.channel'] ?? $container->getSylius_Repository_ChannelService()), ($container->services['sylius.email_sender'] ?? $container->load('getSylius_EmailSenderService')));
    }
}
