<?php

namespace ContainerPxokFAr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Api_Validator_ChosenShippingMethodEligibilityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.api.validator.chosen_shipping_method_eligibility' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Validator\Constraints\ChosenShippingMethodEligibilityValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Validator/Constraints/ChosenShippingMethodEligibilityValidator.php';

        return $container->privates['sylius.api.validator.chosen_shipping_method_eligibility'] = new \Sylius\Bundle\ApiBundle\Validator\Constraints\ChosenShippingMethodEligibilityValidator(($container->services['sylius.repository.shipment'] ?? $container->load('getSylius_Repository_ShipmentService')), ($container->services['sylius.repository.shipping_method'] ?? $container->getSylius_Repository_ShippingMethodService()), ($container->services['sylius.shipping_methods_resolver'] ?? $container->getSylius_ShippingMethodsResolverService()));
    }
}
