<?php

namespace ContainerPxokFAr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_CommandBus_Middleware_HandleMessageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.command_bus.middleware.handle_message' shared service.
     *
     * @return \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/MiddlewareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Middleware/HandleMessageMiddleware.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlersLocator.php';

        $container->privates['sylius.command_bus.middleware.handle_message'] = $instance = new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\HandlersLocator(['Sylius\\Bundle\\ApiBundle\\Command\\RegisterShopUser' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.9S8OWos'] ?? $container->load('get_Messenger_HandlerDescriptor_9S8OWosService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Cart\\PickupCart' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.brdpRYI'] ?? $container->load('get_Messenger_HandlerDescriptor_BrdpRYIService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Cart\\AddItemToCart' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.0xzlWIZ'] ?? $container->load('get_Messenger_HandlerDescriptor_0xzlWIZService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Cart\\RemoveItemFromCart' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.cfnWDjm'] ?? $container->load('get_Messenger_HandlerDescriptor_CfnWDjmService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Checkout\\AddressOrder' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.IYhH9Ts'] ?? $container->load('get_Messenger_HandlerDescriptor_IYhH9TsService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Checkout\\ChooseShippingMethod' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.8T.AZ2y'] ?? $container->load('get_Messenger_HandlerDescriptor_8T_AZ2yService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Checkout\\ChoosePaymentMethod' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.34eMvh4'] ?? $container->load('get_Messenger_HandlerDescriptor_34eMvh4Service'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Checkout\\CompleteOrder' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.eUZtbq4'] ?? $container->load('get_Messenger_HandlerDescriptor_EUZtbq4Service'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Checkout\\ShipShipment' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.er8RVdg'] ?? $container->load('get_Messenger_HandlerDescriptor_Er8RVdgService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Account\\ChangePaymentMethod' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.gaPatef'] ?? $container->load('get_Messenger_HandlerDescriptor_GaPatefService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Cart\\ChangeItemQuantityInCart' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.N3P_9Tt'] ?? $container->load('get_Messenger_HandlerDescriptor_N3P9TtService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\AddProductReview' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.gzfVfBH'] ?? $container->load('get_Messenger_HandlerDescriptor_GzfVfBHService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\BlameCart' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.2xnlrOQ'] ?? $container->load('get_Messenger_HandlerDescriptor_2xnlrOQService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\ChangeShopUserPassword' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.vHkpfDf'] ?? $container->load('get_Messenger_HandlerDescriptor_VHkpfDfService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\RequestResetPasswordToken' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.kFuFk7T'] ?? $container->load('get_Messenger_HandlerDescriptor_KFuFk7TService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\ResendVerificationEmail' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.YZmLxhU'] ?? $container->load('get_Messenger_HandlerDescriptor_YZmLxhUService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\ResetPassword' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.j6k9CM7'] ?? $container->load('get_Messenger_HandlerDescriptor_J6k9CM7Service'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\Cart\\ApplyCouponToCart' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.7TaeyEu'] ?? $container->load('get_Messenger_HandlerDescriptor_7TaeyEuService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\SendAccountRegistrationEmail' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.0D2v_ZB'] ?? $container->load('get_Messenger_HandlerDescriptor_0D2vZBService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\SendAccountVerificationEmail' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.puCB6le'] ?? $container->load('get_Messenger_HandlerDescriptor_PuCB6leService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\SendOrderConfirmation' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.wl5iF0x'] ?? $container->load('get_Messenger_HandlerDescriptor_Wl5iF0xService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\SendResetPasswordEmail' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.XuFm8Bj'] ?? $container->load('get_Messenger_HandlerDescriptor_XuFm8BjService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\SendShipmentConfirmationEmail' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.YuwdS_c'] ?? $container->load('get_Messenger_HandlerDescriptor_YuwdSCService'));
        }, 1), 'Sylius\\Bundle\\ApiBundle\\Command\\VerifyCustomerAccount' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.XCo9MX.'] ?? $container->load('get_Messenger_HandlerDescriptor_XCo9MX_Service'));
        }, 1)]));

        $instance->setLogger(($container->privates['monolog.logger.messenger'] ?? $container->load('getMonolog_Logger_MessengerService')));

        return $instance;
    }
}
