<?php

namespace ContainerPxokFAr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Listener_ApiCartBlamerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.listener.api_cart_blamer' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\EventListener\ApiCartBlamerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/EventListener/ApiCartBlamerListener.php';

        return $container->privates['sylius.listener.api_cart_blamer'] = new \Sylius\Bundle\ApiBundle\EventListener\ApiCartBlamerListener(($container->services['sylius.context.cart'] ?? $container->getSylius_Context_CartService()), ($container->services['sylius.section_resolver.uri_based_section_resolver'] ?? $container->load('getSylius_SectionResolver_UriBasedSectionResolverService')), ($container->services['messenger.default_bus'] ?? $container->getMessenger_DefaultBusService()));
    }
}
