<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPxokFAr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPxokFAr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPxokFAr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPxokFAr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPxokFAr\App_KernelDevDebugContainer([
    'container.build_hash' => 'PxokFAr',
    'container.build_id' => '5b2ceaab',
    'container.build_time' => 1644844320,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPxokFAr');
